# Generated by Django 2.1.5 on 2022-06-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_post2_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='name',
        ),
        migrations.AddField(
            model_name='post2',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
