# Generated by Django 2.1.5 on 2022-06-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220621_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post2',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
