# Generated by Django 2.1.5 on 2022-06-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220621_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.CharField(choices=[('Africa', '아프리카'), ('Europe', '유럽'), ('Oceania', '오세아니아'), ('Asia', '아시아'), ('North America', '북아메리카'), ('South America', '남아메리카')], default='Asia', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, help_text='경도,위도 포맷으로 입력', max_length=50, verbose_name='위경도'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=100, verbose_name='태그'),
        ),
    ]
